<div class="text-center">
	<span class="fa-stack fa-4x">
		<i class="fa fa-pencil fa-stack-1x icon"></i>
	</span>

	<h2 class="titre-article">Ajouter - Editer un article :</h2>
	<span class="separation-noir"> </span>
	<span class="separation-vert"> </span>
	<div class="error">
		<?=$error?>
	</div>
</div>

<form class="form-style" method="POST">
	<div class="form-group clearfix">
		<label for="title">Titre : </label>
		<input class="input" type="text" name="title" placeholder="<?=$title?>" value="<?=$titleEdit?>"/>
	</div>
	<div class="form-group clearfix">
		<label for="imgUrl">Illustration (url) : </label>
		<input class="input" type="url" name="imgUrl" placeholder="<?=$imgUrl?>" value="<?=$imgUrlEdit?>"/>
	</div>
	<div class="form-group clearfix">
		<label for="description">Description : </label>
		<textarea class="input" name="description" cols="30" rows="3"><?=$description?></textarea>
	</div>
	<div class="form-group clearfix">
		<label for="content">Contenu : </label>
		<textarea class="input"name="content" cols="30" rows="10"><?=$content?></textarea>
	</div>

	<div class="text-center"><button class="valid-button" type="submit" name="createDate" value="<?=$createDate?>">Submit</button></div>
</form>