<article>
	<img class"image-article" src="<?=$image?>" alt="">

	<div class="bloc-article">
		<div class="menu-burger-container">
		<?php require "apps/contents/menu_burger.php"; ?>
		</div>
			
		<div class="article">	
			<h1 class="titre-article"><?=$title?></h1>
			<p class="date-article"><?=$createDate?></p>

			<div class="text-article">
				<p><?=$content?></p>
			</div>
			
			<div>
				<a href="index.php?page=commentaires&articleid=<?=$articleid?>">Ajouter un commentaire</a>
			</div>

			<p class="author"><?=$author?></p>
			<p><?php require "apps/contents/display_commentaires.php"; ?></p>
		</div>
	</div>
</article>