<article class="container-article">
	<div class="bloc-article">
		<img class"image-article" src="<?=$image?>" alt="">
		
		<div class="menu-burger">
		<?php require "apps/contents/menu_burger.php"; ?>
		</div>
		
		<div class="article">
			<h1><?=$title?></h1>
			<p><?=$createDate?></p>
		</div>

		<div class="text-article">
			<p><?=$content?></p>
		</div>
		
		<div>
			<p><?=$author?></p>
			<p><?php require "apps/contents/commentaires.php"; ?></p>
		</div>
	</div>
</article>