<h1>Commenter un article :</h1>

<div class="error">
	<?=$error?>
</div>

<form method="POST">
	<div>
		<label for="title">Titre : </label>
		<input type="text" name="title" placeholder="" />
	</div>

	<div>
		<label for="imgUrl">Illustration (url) : </label>
		<input type="url" name="imgUrl" placeholder="" />
	</div>

	<div>
		<label for="description">Description : </label>
		<textarea name="description" cols="30" rows="3"></textarea>
	</div>

	<button type="submit">Submit</button>
</form>