<div class="text-center">
	<div class="error">
		<?=$error?>
	</div>
</div>

<form class="form-style" method="POST">
	<div class="form-group clearfix">
		<label for="content">Commenter un article: </label>
		<textarea class="input" name="content" cols="30" rows="3"><?=$commContent['content']?></textarea>
	</div>

	<input type="hidden" name="author" value="<?=$author?>">
	<input type="hidden" name="articleid" value="<?=$articleid?>">
	<input type="hidden" name="commid" value="<?=$commid?>">
	<input type="hidden" name="action" value="<?=$action?>">
	<div class="text-center"><input class="valid-button" type="submit" value="Valider"/></div>
	
</form>