<h1>Commenter un article :</h1>

<div class="error">
	<?=$error?>
</div>

<form method="POST">
	<div>
		<label for="content">Commentaire : </label>
		<textarea name="content" cols="30" rows="3"><?=$commContent['content']?></textarea>
	</div>

	<input type="hidden" name="author" value="<?=$author?>">
	<input type="hidden" name="articleid" value="<?=$articleid?>">
	<input type="hidden" name="commid" value="<?=$commid?>">
	<input type="hidden" name="action" value="<?=$action?>">
	<input type="submit" value="Valider"/>
</form>