<article>
	<div class="bloc-article">
		<img class="image-article" src="<?=$article['image']?>" alt"illustration article">
		<div class="menu-burger">
			<?php require "apps/contents/menu_burger.php"; ?>
		</div>
		<div class="article">
			<h1><?=$article['title']?></h1>
			<p><?=$article['date']?></p>
		</div>
		<div class="text-article"> 
			<p><?=$article['description']?></p>
		</div>
			
		<div class="footer-article">
			<p><?=$article['author']?></p>
			<a href="index.php?page=article?#commentaires"><?=$nbrComm?> commentaires.</a>
		</div>
	</div>
</article>