<div class="">
	<div class="">

		<h2 class="">S'identifier</h2>
	</div>
	<div class="error">
		<?=$error?>
	</div>
	
	<form class="form-style" method="POST">
		<div class="input-style clearfix">
			<label for="email">E-mail :</label>
			<input class="input" type="email" name="email" />
		</div>
		<div class="input-style clearfix">
			<label for="password">Mot de Passe :</label>
			<input class="input" type="password" name="password" />
		</div>
		
		<div class="text-center">
			<input class="valid-button" type="submit" value="Valider" />
		</div>
	</form>
	
</div>