<h1>Register</h1>

<div class="error">
	<?=$error?>
</div>

<form method="POST">
	<div class="form-group">
		<label for="inputPseudo">Pseudo</label>
		<input name="pseudo" type="text" autofocus class="form-control" id="inputPseudo" placeholder="Pseudo">
	</div>

	<div class="form-group">
		<label for="inputEmail">E-mail</label>
		<input name="email" type="email" autofocus class="form-control" id="inputEmail" placeholder="E-mail">
	</div>

	<div class="form-group">
		<label for="inputConfirmEmail">Confirm E-mail</label>
		<input name="confirmEmail" type="email" autofocus class="form-control" id="inputConfirmEmail" placeholder="Confirm E-mail">
	</div>

	<div class="form-group">
		<label for="inputPassword">Password</label>
		<input name="password" type="password" class="form-control" id="inputPassword" placeholder="Password">
	</div>

	<div class="form-group">
		<label for="inputConfirmPassword">Confirm Password</label>
		<input name="confirmPassword" type="password" class="form-control" id="inputConfirmPassword" placeholder="Confirm Password">
	</div>

	<button type="submit">Submit</button>
</form>