<div class="register-container">
	<div class="titre-register text-center">
		<span class="fa-stack fa-4x">
			<i class="fa fa-user-plus fa-stack-1x icon"></i>
		</span>
	
		<h1>Register</h1>
		<span class="separation-noir"> </span>
		<span class="separation-vert"> </span>
		<div class="error">
			<?=$error?>
		</div>
	</div>

	

	<form class="form-style" method="POST">
		<div class="form-group clearfix">
			<label for="inputPseudo">Login</label>
			<input name="login" type="text" autofocus class="input" id="inputPseudo" placeholder="Login">
		</div>

		<div class="form-group clearfix">
			<label for="inputEmail">E-mail</label>
			<input name="email" type="email" autofocus class="input" id="inputEmail" placeholder="E-mail">
		</div>

		<div class="form-group clearfix">
			<label for="inputConfirmEmail">Confirm E-mail</label>
			<input name="confirmEmail" type="email" autofocus class="input" id="inputConfirmEmail" placeholder="Confirm E-mail">
		</div>

		<div class="form-group clearfix">
			<label for="inputPassword">Password</label>
			<input name="password" type="password" class="input" id="inputPassword" placeholder="Password">
		</div>

		<div class="form-group clearfix">
			<label for="inputConfirmPassword">Confirm Password</label>
			<input name="confirmPassword" type="password" class="input" id="inputConfirmPassword" placeholder="Confirm Password">
		</div>
		<div class="text-center"><input class="valid-button" type="submit" value="valider"></div>
		
	</form>
</div>